blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^search/$',views.search, name='search'),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from img import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls')),
    url(r'^comtents/', include('comments.urls')),
    url(r'^img/', include('img.urls')),
    url(r'^index', views.homePage, name='homepage'),
    url(r'^$', views.homePage, name='homepage'),
]

img/urls.py
__author__ = 'jun'
from django.conf.urls import url
from django.contrib import admin
from img import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'img'
urlpatterns = [
    url(r'^show', views.showImg, name='show'),
    url(r'^uploadpage', views.upload, name='uploadpage'),
    url(r'^done', views.Done, name='done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pic/Homepage.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="stylesheet" type="text/css" href="/static/pic/css/style.css">
<title></title>
</head>

<body>
	<div class="header">
		<div class="top">
			<div class="wp">
				<div class="z">
					<span>
						<a href="">设为首页</a>
					</span>
					<span>
						<a href="">收藏本站</a>
					</span>
				</div>
				<div class="y">
					<span>2015年5月1日</span>
					<span class="mr_0">多云16℃/30℃</span>
				</div>
			</div>
		</div>
		<div class="wp">
			<div class="logos">
				<div class="logo z">
					<h1><a href="index.html"><img src="/static/pic/images/logo.jpg" alt="HTML+CSS实战"/></a></h1>
				</div>
				<div class="tel y">
					<span>联系叔叔：13585536647</span>
				</div>
				<div class="search y">
					<form action="index.html" method="POST">
						<table class="sreach-table"cellpadding="0" cellspacing="0">
							<tr>
								<td class="search_z z"></td>
								<td class="search_c z">
									<input type="text" name="text" id="search_c"/>
								</td>
								<td class="search_y z">
									<button type="submit" name="sumit"></button>
								</td>
							</tr>					
						</table>
					</form>
				</div>			
			</div>	
		</div>
		<div class="nav">
			<div class="wp">
			  <ul>
			  	<li class="a">
			  		<a href="{% url 'homepage' %}">网站首页</a>
			  	</li>
			  	<li>
			  		<a href="{% url 'blog:index' %}">博客</a>
			  	</li>
			  	<li>
			  		<a href="{% url 'img:show' %}">照片</a>
			  	</li>
			  	<li>
			  		<a href="index.html">服务范围</a>
			  	</li>
			  	<li>
			  		<a href="index.html">产品中心</a>
			  	</li>
			  	<li>
			  		<a href="index.html">人才首页</a>
			  	</li>
			  	<li>
			  		<a href="index.html">在线留言</a>
			  	</li>
			  	<li>
			  		<a href="index.html">联系我们</a>
			  	</li>
			  </ul>
			</div>
		</div>
	</div>


	<div class="center">
		<div class="wp">
			<div class="ad">
					<a herf="index.html"><img src="/static/pic/images/banner.jpg" alt="这里是banner" width="960px"
				height="275px"/></a>		
			</div>
		    <div class="intro z">
		    	<div class="title">
		    		<img src="/static/pic/images/intro.jpg" alt="公司简介">
		    		<span><a href="">More</a></span>
		    	</div>
		    	<div class="intro_content">
		    		<img src="/static/pic/images/gongsi.jpg" alt="公司" width="200px" height="111px" class="y"/>

					<p>
		    	    瀑布的水逆流而上<br>
                    蒲公英种子从远处飘回，聚成伞的模样，<br>
                    太阳从西边升起，落向东方。<br>
		    	    </p>
		    	    <p>
		    	    子弹退回枪膛，<br>
                    运动员回到起跑线，<br>
                    我交回录取通知书，忘了十年寒窗。<br>
		    	    </p>
		    	    <p>
		    	    厨房里飘来饭菜的香，<br>
                    你把我的卷子签好名字，关掉电视，<br>
                    帮我把书包背上。<br>
		    	    </p>
		    	    <p>
		    	    你还在我身旁。
		    	    </p>
		    	</div>
		    </div>
		    <div class="news z">
		    	<div class="title">
		    		<img src="/static/pic/images/news.jpg" alt="公司新闻">
		    		<span><a href="{% url 'homepage' %}">More</a></span>
		    	</div>
		    	<div class="news_c">
		    		<ul>
		    			<li class="a">
							<!--
		    				<a href="">
		    				    <img src="/static/pic/images/xinwen.jpg" alt="新闻图片" width="100px" height="90px"/>
		    				    <h3>叔叔最爱baby了！</h3>
		    				    <p>这不是废话嘛！还用你说！！！叔叔最最最最最最最爱小baby了！！！！！</p>
		    				</a>
		    				-->
		    			</li>
						{% for post in blogs %}
		    			<li>
		    				<a href="{{ post.get_absolute_url }}">
		    					<h3>{{ post.title }}</h3>
		    					<span>2017年5月22日</span>
		    				</a>
		    			</li>
						{% endfor %}
		    		</ul>
		    	</div>
		    </div>
		    <div class="product z">
		    	<div class="title">
		    		<img src="/static/pic/images/product.jpg" alt="公司产品">
		    		<span><a href="{% url 'img:show' %}">More</a></span>
		    	</div>
		    	<div class="product_c">
		    		<ul>
						{% for img in imgs %}
		    			<li>
		    				<a href="img/{{ img.img.url }}">
		    					<img src="img/{{ img.img.url }}" alt="图片" height="130px"/>
		    					<span>{{ img.title }}</span>
		    				</a>
		    			</li>
						{% endfor %}
		    		</ul>
		    	</div>
		    </div>
		</div>
	</div>
	<div class="cl"></div>

	<div class="footer">
		<div class="wp">
			<div class="footer_top">
				<span class="z">
					<a href="">关于我们 </a>  |
					<a href=""> 联系我们 </a>  |
					<a href=""> 加入我们 </a>  |
					<a href=""> 给我留言</a>  
				</span>
				<span class="y">版权</span>
		    </div>
		    <div class="footer_bottom">
		    	<p>
		    	    友情链接：  <a href="" target="_blank">叔叔网</a><a href="" target="_blank">baby网</a>
		    	</p>
		    </div>
		</div>	
	</div>
	<div class="fudong">
		<img src="/static/pic/images/weixin.jpg"/>
	</div>
</body>
</html>

templates/pic/done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
    上传成功</br>
    <a href="{% url 'img:uploadpage' %}">上传照片</a></br>
    <a href="{% url 'img:show' %}">查看照片</a>
</body>
</html>

templates/pic/index.html
<!doctype html>
<html lang="zh">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>小笨窝的画廊</title>

	<link rel="stylesheet" type="text/css" href="css/default.css">
	<link href="/static/pic/css/Icomoon/style.css" rel="stylesheet" type="text/css" />
	<link href="/static/pic/css/animated-masonry-gallery.css" rel="stylesheet" type="text/css" />
	<!-- Normalize -->

	<link rel="stylesheet" href="/static/pic/css/assets/normalize.css" type="text/css">

	<!-- Bootstrap -->

	<link href="/static/pic/css/assets/bootstrap.min.css" rel="stylesheet" type="text/css">

	<!-- Font-awesome.min -->

	<link href="/static/pic/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	<!-- Effet -->

	<link rel="stylesheet" href="/static/pic/css/gallery/foundation.min.css"  type="text/css">
	<link rel="stylesheet" type="text/css" href="/static/pic/css/gallery/set1.css" />

	<!-- Main Style -->

	<link rel="stylesheet" href="/static/pic/css/main.css" type="text/css">

	<!-- Responsive Style -->

	<link href="/static/pic/css/responsive.css" rel="stylesheet" type="text/css">

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->

	<!--[if lt IE 9]>

		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>

		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

		<![endif]-->

	<script src="/static/pic/js/assets/modernizr-2.8.3.min.js" type="text/javascript"></script>
	
</head>
<body>

	<div id="gallery">
		<div id="gallery-header">
			<div id="gallery-header-center">
				<div id="gallery-header-center-left">
					<div id="gallery-header-center-left-icon"><span class="iconb" data-icon="&#xe23a;"></span></div>
					<div id="gallery-header-center-left-title">所有图片</div>
				</div>
				<div id="gallery-header-center-right">
					<div class="gallery-header-center-right-links" id="filter-all">所有</div>
					<div class="gallery-header-center-right-links" id="filter-studio">baby</div>
					<div class="gallery-header-center-right-links" id="filter-landscape">叔叔</div>
				</div>
			</div>
		</div>
		</div>


		<div id="gallery-content">
			<div id="gallery-content-center">
				{% for img in imgs %}

					<a href="{{ img.img.url }}" ><img src='{{ img.img.url }}' class='all {{ img.tag.name }}' /></a>
				{% empty %}
						<div class="no-post">暂时还没有图片！</div>
				{% endfor %}
			</div>
		</div>
	</div>

<!--
	<div class="wrapper">
    <div class="">
      <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-3 masonry">
		  {% for img in imgs %}
          <li class="masonry-item grid">
              <figure class="effect-sarah"><a href="{{ img.img.url }}" > <img src="{{ img.img.url }}" alt="" class='all {{ img.tag.name }}'/></a>
                  <figcaption>
				  <h2>{{ img.title }}</h2>
				  <p>{{ img.description }}</p>
				  <a href="{{ img.img.url }}">View more</a> </figcaption>
			  </figure>
			</li>
		  {% empty %}
		      <div class="no-post">暂时还没有图片！</div>
		  {% endfor %}
		  </ul>
		</div>
-->
	<script type="text/javascript" src="/static/pic/js/jquery.min.js" charset="UTF-8"></script>
	<script type="text/javascript" src="/static/pic/js/jquery-ui.min.js" charset="UTF-8"></script>
	<script type="text/javascript" src="/static/pic/js/jquery.isotope.min.js" charset="UTF-8"></script>
	<script type="text/javascript" src="/static/pic/js/animated-masonry-gallery.js" charset="UTF-8"></script>

	<div style="text-align:center;">

</div>
</body>
<script src="/static/pic/js/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/assets/jquery.min.js"><\/script>')</script>
<script src="/static/pic/js/assets/plugins.js" type="text/javascript"></script>
<script src="/static/pic/js/assets/bootstrap.min.js" type="text/javascript"></script>

<script src="/static/pic/js/maps.js" type="text/javascript"></script>
<script src="/static/pic/js/custom.js" type="text/javascript"></script>
<script src="/static/pic/js/jquery.contact.js" type="text/javascript"></script>
<script src="/static/pic/js/main.js" type="text/javascript"></script>
<script src="/static/pic/js/gallery/masonry.pkgd.min.js" type="text/javascript"></script>
<script src="/static/pic/js/gallery/imagesloaded.pkgd.min.js" type="text/javascript"></script>
<script src="/static/pic/js/gallery/jquery.infinitescroll.min.js" type="text/javascript"></script>
<script src="/static/pic/js/gallery/main.js" type="text/javascript"></script>
<script src="/static/pic/js/jquery.nicescroll.min.js" type="text/javascript"></script>
</html>

templates/pic/index1.html
<!DOCTYPE html>

<html class="no-js"  lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
<title>:: Picxa :: A Photographer Portfolio Template</title>

<!-- Normalize -->

<link rel="stylesheet" href="css/assets/normalize.css" type="text/css">

<!-- Bootstrap -->

<link href="css/assets/bootstrap.min.css" rel="stylesheet" type="text/css">

<!-- Font-awesome.min -->

<link href="css/font-awesome.min.css" rel="stylesheet" type="text/css">

<!-- Effet -->

<link rel="stylesheet" href="css/gallery/foundation.min.css"  type="text/css">
<link rel="stylesheet" type="text/css" href="css/gallery/set1.css" />

<!-- Main Style -->

<link rel="stylesheet" href="css/main.css" type="text/css">

<!-- Responsive Style -->

<link href="css/responsive.css" rel="stylesheet" type="text/css">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->

<!--[if lt IE 9]>

      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>

      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

<script src="js/assets/modernizr-2.8.3.min.js" type="text/javascript"></script>
</head>

<body>

<!-- header -->

<header id="header" class="header">
  <div class="container-fluid">
    <hgroup> 
      
      <!-- logo -->
      
      <h1> <a href="index1.html" title="Picxa"><img src="images/logo.png" alt="Picxa" title="Picxa"/></a> </h1>
      
      <!-- logo --> 
      
      <!-- nav -->
      
      <nav>
        <div class="menu-expanded">
          <div class="nav-icon">
            <div id="menu" class="menu"></div>
            <p>menu</p>
          </div>
          <div class="cross"> <span class="linee linea1"></span> <span class="linee linea2"></span> <span class="linee linea3"></span> </div>
          <div class="main-menu">
            <ul>
              <li class="active"><a href="index.html">Home</a></li>
              <li><a href="about.html">About</a></li>
              <li><a href="blog.html">blog</a></li>
              <li><a href="contact.html">contact</a></li>
            </ul>
          </div>
        </div>
      </nav>
      
      <!-- nav --> 
      
    </hgroup>
  </div>
</header>

<!-- header -->
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >企业网站模板</a></div>

<main class="main-wrapper" id="container"> 
  
  <!-- image Gallery -->
  
  <div class="wrapper">
    <div class="">
      <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-3 masonry">
        <li class="masonry-item grid">
          <figure class="effect-sarah"> <img src="{{ img.img.url }}" alt="" />
            <figcaption>
              <h2>Photo <span>Title</span></h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
              <a href="details.html">View more</a> </figcaption>
          </figure>
        </li>
      </ul>
    </div>
  </div>
</main>

<!-- Image Gallery --> 

<!-- footer -->

<footer class="footer">
  <h3>Stay connected with us</h3>
  <div class="container footer-bot">
    <div class="row"> 
      
      <!-- logo -->
      
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3"> <img src="images/footer-logo.png" alt="Picxa" title="Picxa"/>
        <p class="copy-right">&copy; Reserved Picxa inc 2016.</p>
      </div>
      
      <!-- logo --> 
      
      <!-- address -->
      
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 padding-top">
        <address>
        <p>200 Broadway Av</p>
        <p>West Beach SA 5024  Australia</p>
        </address>
      </div>
      
      <!-- address --> 
      
      <!-- email -->
      
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 padding-top">
        <p><a href="mailto:contact@Picxa.com">contact@Picxa.com</a></p>
        <p>01 (2) 34 56 78</p>
      </div>
      
      <!-- email --> 
      
      <!-- social -->
      
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 padding-top">
        <ul class="social">
          <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
          <li><a href="#"><i class="fa fa-flickr" aria-hidden="true"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
          <li><a href="#"><i class="fa fa-tripadvisor" aria-hidden="true"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
          <li><a href="#"><i class="fa fa-delicious" aria-hidden="true"></i></a></li>
        </ul>
        <p class="made-by">Made with by <i class="fa fa-heart" aria-hidden="true"></i> <a href="http:///" target="_blank">Designstub</a>
        <p> 
      </div>
      
      <!-- social --> 
      
    </div>
  </div>
</footer>

<!-- footer --> 

<!-- jQuery --> 

<script src="js/jquery.min.js"></script> 
<script>window.jQuery || document.write('<script src="js/assets/jquery.min.js"><\/script>')</script> 
<script src="js/assets/plugins.js" type="text/javascript"></script> 
<script src="js/assets/bootstrap.min.js" type="text/javascript"></script> 

<script src="js/maps.js" type="text/javascript"></script> 
<script src="js/custom.js" type="text/javascript"></script> 
<script src="js/jquery.contact.js" type="text/javascript"></script> 
<script src="js/main.js" type="text/javascript"></script> 
<script src="js/gallery/masonry.pkgd.min.js" type="text/javascript"></script> 
<script src="js/gallery/imagesloaded.pkgd.min.js" type="text/javascript"></script> 
<script src="js/gallery/jquery.infinitescroll.min.js" type="text/javascript"></script> 
<script src="js/gallery/main.js" type="text/javascript"></script> 
<script src="js/jquery.nicescroll.min.js" type="text/javascript"></script>
</body>
</html>

templates/pic/thumb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% for img in imgs %}
    <img src='{{ img.img.url }}' />
{% empty %}
        <div class="no-post">暂时还没有图片！</div>
    {% endfor %}
</body>
</html>

templates/pic/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    {% if text %}<p><strong>{{ text }}</strong></p>{% endif %}
    <form action="{% url 'img:done' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <input type="file" name="img">
        <div class="col-md-4">
            <label for="{{ form.name.id_for_label }}">标签：</label>
                {% for tag in tags %}
                <input type="radio" name="tag" id="tag{{ forloop.counter }}" value="{{ tag.id }}" />
                <label for="tag{{ forloop.counter }}">{{ tag.name }}</label>
                {% endfor %}
        </div>
        标题：<input type="text" name="title"></br>
        描述：<input type="text" name="description"></br>
        <button type="submit" >上传</button>
    </form>
</body>
</html>

templates/pic/uploadpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    {% if text %}<p><strong>{{ text }}</strong></p>{% endif %}
    <form action="{% url 'img:uploadpage' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <input type="file" name="img">
        <div class="col-md-4">
            <label for="{{ form.name.id_for_label }}">标签：</label>
                {% for tag in tags %}
                <input type="radio" name="tag" id="tag{{ forloop.counter }}" value="{{ tag.id }}" />
                <label for="tag{{ forloop.counter }}">{{ tag.name }}</label>
                {% endfor %}
            </div>
        <button type="submit" >上传</button>
    </form>
</body>
</html>